import type { DaochongReadonlyEndpointSpec } from "./daochongMobile.types";

export const daochongReadonlyEndpointSpecs: DaochongReadonlyEndpointSpec[] = [
  {
    key: "snapshot",
    path: "/api/daochong/mobile/snapshot",
    usedBy: ["home", "performance", "customers", "profile"],
    fields: ["role", "todayStats", "appointments", "alerts", "navBadges"],
  },
  {
    key: "appointments",
    path: "/api/daochong/mobile/appointments",
    usedBy: ["home", "appointment", "settlement", "serviceNote"],
    fields: ["id", "customerId", "teacherId", "projectId", "roomId", "startsAt", "status"],
  },
  {
    key: "appointmentDetail",
    path: "/api/daochong/mobile/appointments/:appointmentId",
    usedBy: ["appointment", "settlement", "serviceNote", "customerDetail"],
    fields: [
      "id",
      "taskId",
      "customerId",
      "customerName",
      "projectId",
      "projectName",
      "teacherId",
      "teacherName",
      "roomId",
      "startsAt",
      "endsAt",
      "arrivalStatus",
      "serviceStatus",
      "settlementDraftId",
      "serviceNoteId",
      "evidenceAssetIds",
      "readonlyWarnings",
    ],
  },
  {
    key: "customers",
    path: "/api/daochong/mobile/customers",
    usedBy: ["customers", "customerDetail", "appointment", "settlement"],
    fields: ["id", "name", "cardStatus", "remainingTimes", "lastServiceAt", "tags"],
  },
  {
    key: "customerDetail",
    path: "/api/daochong/mobile/customers/:customerId",
    usedBy: ["customerDetail"],
    fields: ["profile", "serviceHistory", "preferences", "notes", "cardBalance"],
  },
  {
    key: "customerCardBalances",
    path: "/api/daochong/mobile/customer-card-balances",
    usedBy: ["customerDetail", "settlement", "approval", "finance"],
    fields: [
      "customerId",
      "cardId",
      "cardName",
      "remainingAmount",
      "remainingTimes",
      "lastRechargeId",
      "lastConsumptionApprovalId",
      "balanceStatus",
      "computedAt",
      "readonlyWarnings",
    ],
  },
  {
    key: "roster",
    path: "/api/daochong/mobile/roster",
    usedBy: ["home", "appointment"],
    fields: ["teacherId", "date", "shift", "roomId", "availableSlots", "activityBlocks"],
  },
  {
    key: "projects",
    path: "/api/daochong/mobile/projects",
    usedBy: ["projects", "appointment", "settlement"],
    fields: ["id", "name", "price", "durationMinutes", "cardConsumptionRule", "commissionRule"],
  },
  {
    key: "settlementDrafts",
    path: "/api/daochong/mobile/settlement-drafts",
    usedBy: ["settlement", "approval", "finance", "customerDetail"],
    fields: [
      "id",
      "appointmentId",
      "customerId",
      "projectId",
      "teacherId",
      "paymentMethod",
      "cardId",
      "originalAmount",
      "discountAmount",
      "discountReason",
      "evidenceIds",
      "referrerName",
      "referralBonusAmount",
      "validationStatus",
      "approvalStatus",
    ],
  },
  {
    key: "consumptionApprovals",
    path: "/api/daochong/mobile/consumption-approvals",
    usedBy: ["approval", "settlement", "finance", "customerDetail"],
    fields: [
      "id",
      "settlementDraftId",
      "customerId",
      "teacherId",
      "cardId",
      "consumeAmount",
      "evidenceIds",
      "discountReason",
      "referrerName",
      "referralBonusAmount",
      "approvalStatus",
      "returnReason",
      "approvedBy",
      "approvedAt",
    ],
  },
  {
    key: "compensation",
    path: "/api/daochong/mobile/compensation-rules",
    usedBy: ["compensation", "performance", "finance"],
    fields: ["teacherId", "teacher", "baseSalary", "manualCommissionRate", "fixedCommissionAmount", "bonusRules", "welfareRules", "effectiveMonth", "version", "readonlyWarnings"],
  },
  {
    key: "recharges",
    path: "/api/daochong/mobile/recharges",
    usedBy: ["recharge", "customerDetail", "finance"],
    fields: [
      "id",
      "customerId",
      "amount",
      "paymentMethod",
      "evidenceIds",
      "cashPhotoIds",
      "cashAmount",
      "cashCustodian",
      "chengchengApprovalStatus",
      "limengReviewStatus",
    ],
  },
  {
    key: "rechargeCreate",
    path: "/api/daochong/mobile/recharges",
    usedBy: ["recharge"],
    fields: [
      "customerId",
      "amount",
      "paymentMethod",
      "evidenceAssetIds",
      "cashPhotoAssetIds",
      "cashAmount",
      "cashCustodianUserId",
      "rechargeStatus=PENDING_CHENGCHENG_APPROVAL",
    ],
  },
  {
    key: "evidenceAssets",
    path: "/api/daochong/mobile/evidence-assets",
    usedBy: ["evidence", "recharge", "settlement", "approval", "finance", "expense", "communication"],
    fields: [
      "id",
      "businessType",
      "businessId",
      "assetType",
      "thumbnailUrl",
      "originalUrl",
      "uploadedBy",
      "visibleRoles",
      "reviewStatus",
      "lockedAt",
      "returnReason",
    ],
  },
  {
    key: "serviceNotes",
    path: "/api/daochong/mobile/service-notes",
    usedBy: ["serviceNote", "customerDetail", "home", "appointment"],
    fields: [
      "id",
      "appointmentId",
      "settlementDraftId",
      "customerId",
      "teacherId",
      "projectId",
      "roomId",
      "sourceType",
      "pendingReason",
      "serviceSummary",
      "customerFeedback",
      "nextSuggestion",
      "preferenceNote",
      "preferenceSyncStatus",
      "noteStatus",
      "dueAt",
      "reminderScheduledAt",
      "remindedAt",
      "completedAt",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    key: "serviceNoteCreate",
    path: "POST /api/daochong/mobile/service-notes",
    usedBy: ["serviceNote", "appointment", "customerDetail"],
    fields: [
      "customerId",
      "teacherId",
      "appointmentId",
      "serviceSummary",
      "customerFeedback",
      "nextSuggestion",
      "preferenceNote",
      "preferences",
      "dueAt",
      "reminderScheduledAt",
    ],
  },
  {
    key: "serviceNoteUpdate",
    path: "PATCH /api/daochong/mobile/service-notes/:serviceNoteId",
    usedBy: ["serviceNote", "customerDetail"],
    fields: [
      "serviceSummary",
      "customerFeedback",
      "nextSuggestion",
      "preferenceNote",
      "noteStatus",
      "completedAt",
      "syncPreferences",
      "preferences",
    ],
  },
  {
    key: "customerPreferences",
    path: "/api/daochong/mobile/customer-preferences",
    usedBy: ["customerDetail", "serviceNote", "appointment"],
    fields: [
      "id",
      "customerId",
      "sourceServiceNoteId",
      "preferenceType",
      "preferenceLabel",
      "preferenceValue",
      "roomPreference",
      "lightPreference",
      "pressurePreference",
      "tabooNotes",
      "hobbyNotes",
      "visibility",
      "lastObservedAt",
      "updatedBy",
      "updatedAt",
    ],
  },
  {
    key: "wecomReminderDryRuns",
    path: "/api/daochong/mobile/wecom-reminder-dry-runs",
    usedBy: ["serviceNote", "home", "profile", "approval", "finance"],
    fields: [
      "id",
      "serviceNoteId",
      "customer",
      "teacher",
      "cardTitle",
      "cardSummary",
      "jumpPage",
      "scheduledAt",
      "dueAt",
      "sentAt",
      "cancelledReason",
      "dryRunPayload",
      "readonlyWarnings",
    ],
  },
  {
    key: "wecomReminderTestSend",
    path: "POST /api/daochong/mobile/wecom-reminders/send-test",
    usedBy: ["serviceNote", "home", "profile"],
    fields: [
      "serviceNoteId",
      "toUser",
      "title",
      "description",
      "notifyUrl",
      "markReminded",
      "DAOCHONG_WECOM_TEST_ALLOWLIST",
    ],
  },
  {
    key: "financeSummary",
    path: "/api/daochong/mobile/finance-summary",
    usedBy: ["finance", "approval", "performance"],
    fields: [
      "summaryMonth",
      "confirmedRechargeAmount",
      "pendingCashCustodyAmount",
      "approvedConsumeAmount",
      "commissionAmount",
      "referralBonusAmount",
      "teamBonusAmount",
      "expenseAmount",
      "evidenceIds",
      "exceptionCount",
      "financeStatus",
      "payrollPreviewStatus",
    ],
  },
  {
    key: "financeEvidenceExceptions",
    path: "/api/daochong/mobile/finance-evidence-exceptions",
    usedBy: ["finance", "evidence"],
    fields: [
      "id",
      "businessType",
      "businessId",
      "assetType",
      "exceptionReason",
      "currentOwner",
      "returnTarget",
      "status",
      "updatedAt",
    ],
  },
  {
    key: "bonusExpenseItems",
    path: "/api/daochong/mobile/bonus-expense-items",
    usedBy: ["finance", "bonus", "expense", "performance"],
    fields: [
      "id",
      "itemType",
      "targetUserId",
      "amount",
      "reason",
      "evidenceIds",
      "submittedBy",
      "financeStatus",
      "summaryMonth",
    ],
  },
  {
    key: "projectCommunications",
    path: "/api/daochong/mobile/project-communications",
    usedBy: ["communication", "home", "profile", "customers"],
    fields: [
      "id",
      "topic",
      "projectScopes",
      "participants",
      "relatedCustomerIds",
      "privacyLevel",
      "discussionSummary",
      "status",
      "createdBy",
      "updatedAt",
    ],
  },
  {
    key: "meetingNotes",
    path: "/api/daochong/mobile/meeting-notes",
    usedBy: ["communication", "profile", "customerDetail"],
    fields: [
      "id",
      "communicationId",
      "title",
      "meetingAt",
      "conclusion",
      "todoItems",
      "ownerUserIds",
      "relatedCustomerIds",
      "attachmentIds",
      "archiveStatus",
    ],
  },
];
