import {
  activityStatuses,
  appointments,
  appointmentDetailFields,
  appointmentDetailStatuses,
  acceptanceCreateRows,
  acceptanceFields,
  acceptancePageRows,
  acceptanceReadonlyRows,
  acceptanceRoleRows,
  acceptanceStatuses,
  acceptanceTimeline,
  apiPlanEndpointRows,
  apiPlanFields,
  apiPlanBlockerRows,
  apiPlanPhaseRows,
  apiPlanPrecheckRows,
  apiPlanRiskRows,
  apiPlanSourceRows,
  apiPlanStatuses,
  apiPlanTimeline,
  approvalDecisionFields,
  approvalDetailFields,
  approvalRows,
  approvalStatuses,
  approvalTimeline,
  compensationFormFields,
  compensationRows,
  compensationStatuses,
  communicationFields,
  communicationRows,
  communicationStatuses,
  communicationTimeline,
  customerPreferenceRows,
  customerProfileFields,
  customerServiceHistory,
  customers,
  evidenceFields,
  evidenceRows,
  evidenceStatuses,
  evidenceTimeline,
  expenseFields,
  expenseRows,
  expenseStatuses,
  financeBonusExpenseRows,
  financeDraftFields,
  financeExceptionRows,
  financeRows,
  financeStatuses,
  financeTimeline,
  homeStats,
  homeStatuses,
  managementStatuses,
  meetingNoteFields,
  meetingNoteStatuses,
  meetingTodoRows,
  memberPermissionStatuses,
  memberRows,
  pageMeta,
  performanceRows,
  performanceStats,
  permissionGroups,
  projectFormFields,
  projectRows,
  projectStatuses,
  rechargeFields,
  rechargeRows,
  rechargeStatuses,
  serviceNoteContextFields,
  serviceNoteDryRunStatuses,
  serviceNoteFields,
  serviceNotePendingRows,
  serviceNoteReminderFields,
  serviceNoteReminderTimeline,
  serviceNoteStatuses,
  settlementDraftFields,
  settlementDraftRows,
  settlementSubmissionTimeline,
  settlementFields,
  settlementStatuses,
  teamBonusFields,
  teamBonusRows,
  teamBonusStatuses,
  todayRosterStatuses,
  weekRosterStatuses,
} from "./daochongMobile.mock";
import { daochongReadonlyEndpointSpecs } from "./daochongMobile.api";
import { buildReadonlyApiSnapshot } from "./daochongMobile.readonly-adapters";
import { isDaochongReadonlyFetchEnabled } from "./daochongMobile.readonly-fetch";
import type { DaochongMobileDataSource, DaochongMobileSnapshot } from "./daochongMobile.types";

const mockSnapshot: DaochongMobileSnapshot = {
  dataSourceDiagnostics: [],
  pageMeta,
  homeStats,
  homeStatuses,
  todayRosterStatuses,
  weekRosterStatuses,
  activityStatuses,
  appointments,
  appointmentDetailFields,
  appointmentDetailStatuses,
  acceptanceFields,
  acceptancePageRows,
  acceptanceRoleRows,
  acceptanceCreateRows,
  acceptanceReadonlyRows,
  acceptanceStatuses,
  acceptanceTimeline,
  apiPlanFields,
  apiPlanPhaseRows,
  apiPlanEndpointRows,
  apiPlanRiskRows,
  apiPlanPrecheckRows,
  apiPlanSourceRows,
  apiPlanBlockerRows,
  apiPlanStatuses,
  apiPlanTimeline,
  performanceStats,
  performanceRows,
  customers,
  customerProfileFields,
  customerServiceHistory,
  customerPreferenceRows,
  approvalStatuses,
  approvalDetailFields,
  approvalRows,
  approvalDecisionFields,
  approvalTimeline,
  settlementFields,
  settlementDraftFields,
  settlementDraftRows,
  settlementSubmissionTimeline,
  settlementStatuses,
  rechargeFields,
  rechargeRows,
  rechargeStatuses,
  evidenceFields,
  evidenceRows,
  evidenceStatuses,
  evidenceTimeline,
  serviceNoteContextFields,
  serviceNoteFields,
  serviceNotePendingRows,
  serviceNoteReminderFields,
  serviceNoteReminderTimeline,
  serviceNoteDryRunStatuses,
  serviceNoteStatuses,
  financeRows,
  financeDraftFields,
  financeExceptionRows,
  financeBonusExpenseRows,
  financeStatuses,
  financeTimeline,
  expenseFields,
  expenseRows,
  expenseStatuses,
  teamBonusFields,
  teamBonusRows,
  teamBonusStatuses,
  communicationFields,
  communicationRows,
  communicationStatuses,
  communicationTimeline,
  meetingNoteFields,
  meetingTodoRows,
  meetingNoteStatuses,
  managementStatuses,
  memberRows,
  memberPermissionStatuses,
  permissionGroups,
  projectRows,
  projectStatuses,
  projectFormFields,
  compensationRows,
  compensationStatuses,
  compensationFormFields,
};

export const daochongMockDataSource: DaochongMobileDataSource = {
  mode: "mock",
  readonlyEndpoints: daochongReadonlyEndpointSpecs,
  getSnapshot: () => mockSnapshot,
};

export const daochongReadonlyApiDataSource: DaochongMobileDataSource = {
  mode: "api-readonly",
  readonlyEndpoints: daochongReadonlyEndpointSpecs,
  // The API source is intentionally read-only and falls back to mock data until real endpoint calls are approved.
  getSnapshot: () =>
    buildReadonlyApiSnapshot(
      mockSnapshot,
      {},
      isDaochongReadonlyFetchEnabled(daochongReadonlyApiDataSource)
        ? undefined
        : {
            projects: {
              status: "disabled",
              note: "真实项目只读请求开关关闭，当前显示 mock 项目",
            },
            roster: {
              status: "disabled",
              note: "真实班表只读请求开关关闭，当前显示 mock 班表",
            },
            compensationRules: {
              status: "disabled",
              note: "薪酬配置只读请求开关关闭，当前显示 mock 薪酬配置",
            },
            wecomReminderDryRuns: {
              status: "disabled",
              note: "企微提醒 dry-run 只读请求开关关闭，当前显示 mock 提醒预览",
            },
          },
    ),
};

export function getDaochongMobileDataSource(): DaochongMobileDataSource {
  if (process.env.NEXT_PUBLIC_DAOCHONG_MOBILE_DATA_SOURCE === "api-readonly") {
    return daochongReadonlyApiDataSource;
  }
  return daochongMockDataSource;
}
