-- DCM-85 local migration file.
-- Generated for local review only in this turn. Do not run until Go/No-Go is approved.

CREATE TABLE `DaochongServiceNote` (
  `id` varchar(191) NOT NULL,
  `appointmentId` varchar(191) NULL,
  `settlementDraftId` varchar(191) NULL,
  `customerId` varchar(191) NOT NULL,
  `teacherId` varchar(191) NOT NULL,
  `projectId` varchar(191) NULL,
  `roomId` varchar(64) NULL,
  `sourceType` enum('APPOINTMENT_COMPLETED','SETTLEMENT_DRAFT_CREATED','MANUAL_BACKFILL') NOT NULL DEFAULT 'MANUAL_BACKFILL',
  `pendingReason` varchar(255) NULL,
  `serviceSummary` text NULL,
  `customerFeedback` text NULL,
  `nextSuggestion` text NULL,
  `preferenceNote` text NULL,
  `preferenceSyncStatus` enum('NOT_SYNCED','SYNCED','SKIPPED','REVIEW_REQUIRED') NOT NULL DEFAULT 'NOT_SYNCED',
  `noteStatus` enum('PENDING','COMPLETED','OVERDUE','RETURNED','CANCELLED') NOT NULL DEFAULT 'PENDING',
  `dueAt` datetime(3) NULL,
  `reminderScheduledAt` datetime(3) NULL,
  `remindedAt` datetime(3) NULL,
  `completedAt` datetime(3) NULL,
  `createdByUserId` varchar(191) NULL,
  `dataScope` enum('REAL','TEST') NOT NULL DEFAULT 'REAL',
  `partitionKey` varchar(64) NOT NULL DEFAULT 'REAL',
  `testBatchId` varchar(191) NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `DaochongServiceNote_customerId_idx` (`customerId`),
  KEY `DaochongServiceNote_teacherId_idx` (`teacherId`),
  KEY `DaochongServiceNote_appointmentId_idx` (`appointmentId`),
  KEY `DaochongServiceNote_settlementDraftId_idx` (`settlementDraftId`),
  KEY `DaochongServiceNote_noteStatus_dueAt_idx` (`noteStatus`, `dueAt`),
  KEY `DaochongServiceNote_customerId_completedAt_idx` (`customerId`, `completedAt`),
  KEY `DaochongServiceNote_partitionKey_idx` (`partitionKey`),
  KEY `DaochongServiceNote_testBatchId_idx` (`testBatchId`),
  CONSTRAINT `DaochongServiceNote_customerId_fkey` FOREIGN KEY (`customerId`) REFERENCES `Customer` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `DaochongServiceNote_teacherId_fkey` FOREIGN KEY (`teacherId`) REFERENCES `User` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `DaochongServiceNote_projectId_fkey` FOREIGN KEY (`projectId`) REFERENCES `Product` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `DaochongServiceNote_createdByUserId_fkey` FOREIGN KEY (`createdByUserId`) REFERENCES `User` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE `DaochongCustomerPreference` (
  `id` varchar(191) NOT NULL,
  `customerId` varchar(191) NOT NULL,
  `sourceServiceNoteId` varchar(191) NULL,
  `preferenceType` enum('ROOM','LIGHT','PRESSURE','AROMA','TABOO','HOBBY','OTHER') NOT NULL,
  `preferenceLabel` varchar(128) NOT NULL,
  `preferenceValue` text NOT NULL,
  `roomPreference` varchar(128) NULL,
  `lightPreference` varchar(128) NULL,
  `pressurePreference` varchar(128) NULL,
  `tabooNotes` text NULL,
  `hobbyNotes` text NULL,
  `visibility` enum('SERVICE_TEAM','MANAGEMENT_ONLY','PRIVATE_NOTE') NOT NULL DEFAULT 'SERVICE_TEAM',
  `lastObservedAt` datetime(3) NULL,
  `updatedByUserId` varchar(191) NULL,
  `dataScope` enum('REAL','TEST') NOT NULL DEFAULT 'REAL',
  `partitionKey` varchar(64) NOT NULL DEFAULT 'REAL',
  `testBatchId` varchar(191) NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `DaochongCustomerPreference_customerId_idx` (`customerId`),
  KEY `DaochongCustomerPreference_sourceServiceNoteId_idx` (`sourceServiceNoteId`),
  KEY `DaochongCustomerPreference_customerId_preferenceType_idx` (`customerId`, `preferenceType`),
  KEY `DaochongCustomerPreference_updatedAt_idx` (`updatedAt`),
  KEY `DaochongCustomerPreference_partitionKey_idx` (`partitionKey`),
  KEY `DaochongCustomerPreference_testBatchId_idx` (`testBatchId`),
  CONSTRAINT `DaochongCustomerPreference_customerId_fkey` FOREIGN KEY (`customerId`) REFERENCES `Customer` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `DaochongCustomerPreference_sourceServiceNoteId_fkey` FOREIGN KEY (`sourceServiceNoteId`) REFERENCES `DaochongServiceNote` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `DaochongCustomerPreference_updatedByUserId_fkey` FOREIGN KEY (`updatedByUserId`) REFERENCES `User` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
);
